import sys

def modify():
    with open('app.py', 'r', encoding='utf-8') as f:
        lines = f.readlines()

    out = []
    in_calc = False
    
    for i, line in enumerate(lines):
        if 'st.latex(r"1 + H(s)G(s) = 0 \\Rightarrow 1 + K \\cdot P(s) = 0")' in line:
            out.append('    st.markdown("---")\n')
            out.append('    modo = st.radio("Modo de Exibição", ["Completo (Passo a Passo)", "Simplificado (Foco em Prova)"], horizontal=True)\n')
            out.append('    if modo.startswith("Simplificado"):\n')
            out.append('        tol_deg = st.number_input("Tolerância angular para pertinência (graus)", value=1.0, step=0.1, help="Usado no Item (b) para decidir se o ponto pertence ao LGR.")\n')
            out.append('    else:\n')
            out.append('        tol_deg = 5.0\n')
            out.append('    st.markdown("---")\n')
            out.append(line)
        elif line.strip() == '# Passo 1' and not in_calc:
            in_calc = True
            # Inject simplified mode
            out.append('        if modo.startswith("Simplificado"):\n')
            out.append('            st.markdown("### Selecione o que deseja calcular:")\n')
            out.append('            col_a, col_b = st.columns(2)\n')
            out.append('            with col_a:\n')
            out.append('                show_item_a = st.checkbox("Item (a) - Esboço do LGR", value=True)\n')
            out.append('            with col_b:\n')
            out.append('                show_item_b = st.checkbox("Item (b) - Teste de Ponto", value=True)\n')
            out.append('            \n')
            out.append('            if show_item_a:\n')
            out.append('                st.markdown("### ▼ ITEM (a): ESBOÇO DO LGR (Valores Prontos)")\n')
            out.append('                \n')
            out.append('                def format_root(r):\n')
            out.append('                    r_rounded = np.round(r, 4)\n')
            out.append('                    if abs(np.imag(r_rounded)) < 1e-5:\n')
            out.append('                        return f"{format_frac(np.real(r_rounded))}"\n')
            out.append('                    else:\n')
            out.append('                        sign = "+" if np.imag(r_rounded) > 0 else "-"\n')
            out.append('                        return f"{format_frac(np.real(r_rounded))} {sign} {format_frac(abs(np.imag(r_rounded)))}j"\n')
            out.append('                \n')
            out.append('                p_list = [f"p_{{{i+1}}} = {format_root(p)}" for i, p in enumerate(sorted(poles, key=lambda x: (np.real(x), np.imag(x))))]\n')
            out.append('                z_list = [f"z_{{{i+1}}} = {format_root(z)}" for i, z in enumerate(sorted(zeros, key=lambda x: (np.real(x), np.imag(x))))]\n')
            out.append('                st.markdown("**• Polos de malha aberta:** " + (", ".join([f"${p}$" for p in p_list]) if p_list else "Nenhum polo finito."))\n')
            out.append('                st.markdown("**• Zeros de malha aberta:** " + (", ".join([f"${z}$" for z in z_list]) if z_list else "Nenhum zero finito."))\n')
            out.append('                \n')
            out.append('                real_roots = [np.real(r) for r in np.concatenate((poles, zeros)) if abs(np.imag(r)) < 1e-5]\n')
            out.append('                real_roots = sorted(real_roots, reverse=True)\n')
            out.append('                segments = []\n')
            out.append('                for j in range(0, len(real_roots), 2):\n')
            out.append('                    start = real_roots[j]\n')
            out.append('                    if j + 1 < len(real_roots):\n')
            out.append('                        segments.append(f"[{format_frac(real_roots[j+1])}, {format_frac(start)}]")\n')
            out.append('                    else:\n')
            out.append('                        segments.append(f"(-∞, {format_frac(start)}]")\n')
            out.append('                st.markdown("**• Eixo Real:** Segmentos válidos = " + (", ".join(segments) if segments else "Nenhum segmento no eixo real."))\n')
            out.append('                \n')
            out.append('                ls = max(nP, nZ)\n')
            out.append('                st.markdown(f"**• Ramos (LS):** $\\\\max({nP}, {nZ}) = {ls}$")\n')
            out.append('                \n')
            out.append('                if nP == nZ:\n')
            out.append('                    st.markdown("**• Assíntotas:** Não há assíntotas.")\n')
            out.append('                else:\n')
            out.append('                    sum_p_str = " + ".join([f"({format_complex_frac(p)})" for p in poles]) or "0"\n')
            out.append('                    sum_z_str = " + ".join([f"({format_complex_frac(z)})" for z in zeros]) or "0"\n')
            out.append('                    sigma_a_val = format_frac(np.real(sigma_A))\n')
            out.append('                    st.markdown(f"**• Assíntotas (Centroide):** $\\\\sigma_a = \\\\frac{{[{sum_p_str}] - [{sum_z_str}]}}{{{nP} - {nZ}}} = {sigma_a_val}$")\n')
            out.append('                    angles_A = [(2 * q + 1) * 180 / abs(nP - nZ) for q in range(abs(nP - nZ))]\n')
            out.append('                    angles_str = ", ".join([f"{format_frac(a)}°" for a in angles_A])\n')
            out.append('                    st.markdown(f"**• Assíntotas (Ângulos):** $\\\\theta_k = {angles_str}$")\n')
            out.append('                \n')
            out.append('                st.markdown("**• Pontos de Saída/Entrada:**")\n')
            out.append('                if not valid_breakaway:\n')
            out.append('                    st.markdown("  Não há pontos de saída/entrada válidos.")\n')
            out.append('                else:\n')
            out.append('                    for pt in valid_breakaway:\n')
            out.append('                        if pt[1] < 1e-5:\n')
            out.append('                            st.markdown(f"&nbsp;&nbsp; $s = {format_frac(pt[0])}$ ($K = {format_frac(pt[1])}$) — **(Pólo múltiplo — partida trivial)**")\n')
            out.append('                        elif np.isinf(pt[1]) or pt[1] > 1e10:\n')
            out.append('                            st.markdown(f"&nbsp;&nbsp; $s = {format_frac(pt[0])}$ ($K \\\\to \\\\infty$) — **(Zero múltiplo — chegada trivial)**")\n')
            out.append('                        else:\n')
            out.append('                            st.markdown(f"&nbsp;&nbsp; $s = {format_frac(pt[0])}$ ($K = {format_frac(pt[1])}$)")\n')
            out.append('                \n')
            out.append('                cross_msg = "Não cruza o eixo imaginário (para $K > 0$)." if not omega_vals else "Cruzamentos em: " + ", ".join([f"$s = \\\\pm {format_frac(w)}j$ ($K = {format_frac(routh_result[\'k_crit\'][\'val\'])} $)" for w in omega_vals])\n')
            out.append('                st.markdown(f"**• Cruzamento Eixo $j\\\\omega$:** {cross_msg}")\n')
            out.append('                \n')
            out.append('                st.markdown("---")\n')
            out.append('                \n')
            out.append('            if show_item_b:\n')
            out.append('                st.markdown("### ▼ ITEM (b): TESTE DE PONTO CANDIDATO E GANHO K")\n')
            out.append('                s0_str = format_complex_frac(s0)\n')
            out.append('                st.markdown(f"**Ponto $s_i$:** Re(s): **{format_frac(s0_real)}** | Im(s): **{format_frac(s0_imag)}** $\\\\implies (s = {s0_str})$")\n')
            out.append('                \n')
            out.append('                test_details = evaluate_test_point_details(s0, poles, zeros, D_coeffs, N_coeffs, atol_deg=tol_deg)\n')
            out.append('                sum_z = test_details["sum_z"]\n')
            out.append('                sum_p = test_details["sum_p"]\n')
            out.append('                total_angle = test_details["total_angle"]\n')
            out.append('                is_lgr = test_details["is_lgr"]\n')
            out.append('                K_val = test_details["K_val"]\n')
            out.append('                \n')
            out.append('                sum_z_terms = " + ".join([f"({format_frac(vz[\'angle_deg\'])}°)" for vz in test_details[\'vecs_z\']]) or "0°"\n')
            out.append('                sum_p_terms = " + ".join([f"({format_frac(vp[\'angle_deg\'])}°)" for vp in test_details[\'vecs_p\']]) or "0°"\n')
            out.append('                \n')
            out.append('                st.markdown("**• Critério de Ângulo (Pertinência):**")\n')
            out.append('                if is_lgr:\n')
            out.append('                    st.latex(f"\\\\Sigma \\\\theta_z - \\\\Sigma \\\\theta_p = ({sum_z_terms}) - ({sum_p_terms}) = {format_frac(total_angle)}^\\\\circ \\\\approx \\\\pm 180^\\\\circ")\n')
            out.append('                    st.success(f"**RESULTADO: O PONTO PERTENCE AO LGR (Tolerância: ±{tol_deg}°)**")\n')
            out.append('                    \n')
            out.append('                    st.markdown("**• Critério de Módulo (Cálculo de K):**")\n')
            out.append('                    dist_p_terms = " \\\\cdot ".join([f"{format_frac(vp[\'dist\'])}" for vp in test_details[\'vecs_p\']]) or "1"\n')
            out.append('                    dist_z_terms = " \\\\cdot ".join([f"{format_frac(vz[\'dist\'])}" for vz in test_details[\'vecs_z\']]) or "1"\n')
            out.append('                    scale_factor = (abs(N_coeffs[0])/abs(D_coeffs[0])) if D_coeffs[0] != 0 else 1.0\n')
            out.append('                    scale_str = f"{format_frac(scale_factor)} \\\\cdot " if scale_factor != 1.0 else ""\n')
            out.append('                    st.latex(f"K = \\\\frac{{\\\\prod dist_p}}{{{scale_str}\\\\prod dist_z}} = \\\\frac{{{dist_p_terms}}}{{{scale_str}{dist_z_terms}}} = {format_frac(K_val)}")\n')
            out.append('                    st.success(f"**RESULTADO: K = {format_frac(K_val)}**")\n')
            out.append('                else:\n')
            out.append('                    st.latex(f"\\\\Sigma \\\\theta_z - \\\\Sigma \\\\theta_p = ({sum_z_terms}) - ({sum_p_terms}) = {format_frac(total_angle)}^\\\\circ \\\\neq \\\\pm 180^\\\\circ")\n')
            out.append('                    st.error(f"**RESULTADO: O PONTO NÃO PERTENCE AO LGR (Fora da tolerância de ±{tol_deg}°)**")\n')
            out.append('                \n')
            out.append('        else:\n')
            out.append('    ' + line)  # Indent `# Passo 1` by 4 spaces
        elif in_calc:
            if line.strip() == '':
                out.append(line)
            else:
                out.append('    ' + line)
        else:
            out.append(line)

    with open('app.py', 'w', encoding='utf-8') as f:
        f.writelines(out)

modify()
