import sys

def modify():
    with open('app.py', 'r', encoding='utf-8') as f:
        lines = f.readlines()

    replacement = []
    r = replacement.append

    # Setup the indentation
    ind = "        "
    r(ind + 'if modo.startswith("Simplificado"):\n')
    r(ind + '    st.markdown("### Selecione o que deseja calcular:")\n')
    r(ind + '    col_a, col_b = st.columns(2)\n')
    r(ind + '    with col_a:\n')
    r(ind + '        show_item_a = st.checkbox("Item (a) - Esboço do LGR", value=True)\n')
    r(ind + '    with col_b:\n')
    r(ind + '        show_item_b = st.checkbox("Item (b) - Teste de Ponto", value=True)\n')
    r(ind + '    \n')
    
    r(ind + '    if show_item_a:\n')
    r(ind + '        st.markdown("### ▼ ITEM (a): ESBOÇO DO LGR")\n')
    
    # Passo 1
    r(ind + '        st.markdown("**1. Polinômio característico com K em evidência**")\n')
    r(ind + '        char_poly_str = get_char_poly_latex(D_coeffs, N_coeffs)\n')
    r(ind + '        num_str = format_poly_latex(N_coeffs)\n')
    r(ind + '        den_str = format_poly_latex(D_coeffs)\n')
    r(ind + '        st.latex(r"1 + G(s)H(s) = 1 + K \\frac{" + num_str + r"}{" + den_str + r"} = 0 \Rightarrow " + char_poly_str + " = 0")\n')
    
    # Passo 2
    r(ind + '        st.markdown("**2. Fatoração de P(s)**")\n')
    r(ind + '        num_fact = format_factored_latex(zeros)\n')
    r(ind + '        den_fact = format_factored_latex(poles)\n')
    r(ind + '        K_scale = N_coeffs[0] / D_coeffs[0] if D_coeffs[0] != 0 else 1.0\n')
    r(ind + '        K_str = f"{format_frac(K_scale)}" if K_scale != 1.0 else ""\n')
    r(ind + '        st.latex(r"P(s) = " + K_str + r"\\frac{" + num_fact + r"}{" + den_fact + r"}")\n')
    
    # Passo 3
    r(ind + '        st.markdown("**3. Pólos e zeros de malha aberta**")\n')
    r(ind + '        def format_root(r):\n')
    r(ind + '            r_rounded = np.round(r, 4)\n')
    r(ind + '            if abs(np.imag(r_rounded)) < 1e-5:\n')
    r(ind + '                return f"{format_frac(np.real(r_rounded))}"\n')
    r(ind + '            else:\n')
    r(ind + '                sign = "+" if np.imag(r_rounded) > 0 else "-"\n')
    r(ind + '                return f"{format_frac(np.real(r_rounded))} {sign} {format_frac(abs(np.imag(r_rounded)))}j"\n')
    
    r(ind + '        p_list = [f"p_{{{i+1}}} = {format_root(p)}" for i, p in enumerate(sorted(poles, key=lambda x: (np.real(x), np.imag(x))))]\n')
    r(ind + '        z_list = [f"z_{{{i+1}}} = {format_root(z)}" for i, z in enumerate(sorted(zeros, key=lambda x: (np.real(x), np.imag(x))))]\n')
    r(ind + '        st.markdown("• Polos: " + (", ".join([f"${p}$" for p in p_list]) if p_list else "Nenhum"))\n')
    r(ind + '        st.markdown("• Zeros: " + (", ".join([f"${z}$" for z in z_list]) if z_list else "Nenhum"))\n')
    
    # Passo 4
    r(ind + '        st.markdown("**4. Segmentos do eixo real**")\n')
    r(ind + '        st.markdown("Aplica-se à esquerda de um número ímpar de pólos+zeros no eixo real.")\n')
    r(ind + '        real_roots = [np.real(r) for r in np.concatenate((poles, zeros)) if abs(np.imag(r)) < 1e-5]\n')
    r(ind + '        real_roots = sorted(real_roots, reverse=True)\n')
    r(ind + '        segments = []\n')
    r(ind + '        fig_p34 = create_base_plot(poles, zeros, "Passos 3 e 4: Pólos, Zeros e Eixo Real", xmin, xmax, ymin, ymax)\n')
    r(ind + '        for j in range(0, len(real_roots), 2):\n')
    r(ind + '            start = real_roots[j]\n')
    r(ind + '            if j + 1 < len(real_roots):\n')
    r(ind + '                segments.append(f"[{format_frac(real_roots[j+1])}, {format_frac(start)}]")\n')
    r(ind + '                fig_p34.add_trace(go.Scatter(x=[start, real_roots[j+1]], y=[0, 0], mode="lines", line=dict(color="#00b4d8", width=5), name="LGR Real"))\n')
    r(ind + '            else:\n')
    r(ind + '                segments.append(f"(-∞, {format_frac(start)}]")\n')
    r(ind + '                end_plot = xmin - (xmax - xmin) * 0.1\n')
    r(ind + '                fig_p34.add_trace(go.Scatter(x=[start, end_plot], y=[0, 0], mode="lines", line=dict(color="#00b4d8", width=5), name="LGR Real"))\n')
    r(ind + '                fig_p34.add_annotation(x=end_plot, y=0, ax=start, ay=0, xref="x", yref="y", axref="x", ayref="y", showarrow=True, arrowhead=2, arrowsize=1.2, arrowwidth=3, arrowcolor="#00b4d8")\n')
    r(ind + '        st.markdown("• Segmentos válidos: " + (", ".join(segments) if segments else "Nenhum"))\n')
    r(ind + '        st.plotly_chart(fig_p34, width="stretch", config={"scrollZoom": True})\n')
    
    # Passo 5
    r(ind + '        st.markdown("**5. Número de lugares separados (Ramos)**")\n')
    r(ind + '        ls = max(nP, nZ)\n')
    r(ind + '        st.latex(f"LS = \\\\max(n_P, n_Z) = \\\\max({nP}, {nZ}) = {ls}")\n')
    
    # Passo 6
    r(ind + '        st.markdown("**6. Simetria**")\n')
    r(ind + '        st.markdown("O LGR é simétrico em relação ao eixo real.")\n')
    
    # Passo 7
    r(ind + '        st.markdown("**7. Assíntotas**")\n')
    r(ind + '        if nP == nZ:\n')
    r(ind + '            st.markdown("• Não há assíntotas.")\n')
    r(ind + '        else:\n')
    r(ind + '            sum_p_str = " + ".join([f"({format_complex_frac(p)})" for p in poles]) or "0"\n')
    r(ind + '            sum_z_str = " + ".join([f"({format_complex_frac(z)})" for z in zeros]) or "0"\n')
    r(ind + '            sigma_a_val = format_frac(np.real(sigma_A))\n')
    r(ind + '            st.latex(f"\\\\sigma_A = \\\\frac{{\\\\sum p_i - \\\\sum z_i}}{{n_P - n_Z}} = \\\\frac{{[{sum_p_str}] - [{sum_z_str}]}}{{{nP} - {nZ}}} = {sigma_a_val}")\n')
    r(ind + '            angles_A = [(2 * q + 1) * 180 / abs(nP - nZ) for q in range(abs(nP - nZ))]\n')
    r(ind + '            for q, a in enumerate(angles_A):\n')
    r(ind + '                st.latex(f"\\\\theta_{{{q}}} = \\\\frac{{180^\\\\circ(2({q})+1)}}{{|n_P - n_Z|}} = {format_frac(a)}^\\\\circ")\n')
    
    # Passo 8
    r(ind + '        st.markdown("**8. Pontos de Saída/Entrada**")\n')
    r(ind + '        st.latex(r"1) \\quad K = -P(s)^{-1} \\qquad 2) \\quad \\frac{dK}{ds} = 0")\n')
    r(ind + '        if not valid_breakaway:\n')
    r(ind + '            st.markdown("• Não há pontos de saída/entrada válidos.")\n')
    r(ind + '        else:\n')
    r(ind + '            for pt in valid_breakaway:\n')
    r(ind + '                if pt[1] < 1e-5:\n')
    r(ind + '                    st.markdown(f"• $s = {format_frac(pt[0])}$ ($K = {format_frac(pt[1])}$) — **(Pólo múltiplo — partida trivial)**")\n')
    r(ind + '                elif np.isinf(pt[1]) or pt[1] > 1e10:\n')
    r(ind + '                    st.markdown(f"• $s = {format_frac(pt[0])}$ ($K \\\\to \\\\infty$) — **(Zero múltiplo — chegada trivial)**")\n')
    r(ind + '                else:\n')
    r(ind + '                    st.markdown(f"• $s = {format_frac(pt[0])}$ ($K = {format_frac(pt[1])}$)")\n')
    
    # Passo 9
    r(ind + '        st.markdown("**9. Cruzamento com o eixo jω (Routh-Hurwitz)**")\n')
    r(ind + '        st.markdown(f"Condição de estabilidade gerada para: $D(s) + K \\\\cdot N(s) = 0$")\n')
    r(ind + '        routh_table = routh_result.get("table", [])\n')
    r(ind + '        if routh_table:\n')
    r(ind + '            import sympy as sp\n')
    r(ind + '            mat_str = "\\\\\\\\ ".join([" & ".join([str(sp.simplify(item)) for item in row]) for row in routh_table])\n')
    r(ind + '            st.latex(r"\\begin{bmatrix}" + mat_str + r"\\end{bmatrix}")\n')
    r(ind + '        if not omega_vals:\n')
    r(ind + '            st.markdown("• Não cruza o eixo imaginário (para $K > 0$).")\n')
    r(ind + '        else:\n')
    r(ind + '            for w in omega_vals:\n')
    r(ind + '                st.markdown(f"• Cruzamento em $s = \\\\pm {format_frac(w)}j$ para $K = {format_frac(routh_result[\'k_crit\'][\'val\'])} $")\n')

    # Passo 10
    r(ind + '        st.markdown("**10. Ângulos de Partida e Chegada**")\n')
    r(ind + '        dep_arr = calculate_departure_arrival_angles(poles, zeros, N_coeffs, D_coeffs)\n')
    r(ind + '        if not dep_arr.get("has_complex"):\n')
    r(ind + '            st.markdown("• Não há pólos ou zeros complexos.")\n')
    r(ind + '        else:\n')
    r(ind + '            for pd in dep_arr.get("pole_details", []):\n')
    r(ind + '                sum_p = " + ".join(f"{format_frac(a)}°" for a in pd["angles_p"]) or "0°"\n')
    r(ind + '                sum_z = " + ".join(f"{format_frac(a)}°" for a in pd["angles_z"]) or "0°"\n')
    r(ind + '                st.latex(f"\\\\theta_{{d, {format_complex_frac(pd[\'pole\'])}}} = 180^\\\\circ - ({sum_p}) + ({sum_z}) = {format_frac(pd[\'departure_angle\'])}^\\\\circ")\n')
    r(ind + '            for zd in dep_arr.get("zero_details", []):\n')
    r(ind + '                sum_z = " + ".join(f"{format_frac(a)}°" for a in zd["angles_z"]) or "0°"\n')
    r(ind + '                sum_p = " + ".join(f"{format_frac(a)}°" for a in zd["angles_p"]) or "0°"\n')
    r(ind + '                st.latex(f"\\\\theta_{{a, {format_complex_frac(zd[\'zero\'])}}} = 180^\\\\circ - ({sum_z}) + ({sum_p}) = {format_frac(zd[\'arrival_angle\'])}^\\\\circ")\n')
    
    # Gráfico Final
    r(ind + '        st.markdown("**Esboço Final do LGR:**")\n')
    r(ind + '        K_vec, all_roots = simulate_root_locus(D_coeffs, N_coeffs, nP, nZ)\n')
    r(ind + '        fig_simp = create_base_plot(poles, zeros, "Lugar Geométrico das Raízes (Esboço Final)", xmin, xmax, ymin, ymax)\n')
    
    # Adicionando eixo real
    r(ind + '        for j in range(0, len(real_roots), 2):\n')
    r(ind + '            start = real_roots[j]\n')
    r(ind + '            if j + 1 < len(real_roots):\n')
    r(ind + '                fig_simp.add_trace(go.Scatter(x=[start, real_roots[j+1]], y=[0, 0], mode="lines", line=dict(color="#00b4d8", width=5), name="LGR Real", hoverinfo="skip"))\n')
    r(ind + '            else:\n')
    r(ind + '                end_plot = xmin - (xmax - xmin) * 0.1\n')
    r(ind + '                fig_simp.add_trace(go.Scatter(x=[start, end_plot], y=[0, 0], mode="lines", line=dict(color="#00b4d8", width=5), name="LGR Real", hoverinfo="skip"))\n')
    r(ind + '                fig_simp.add_annotation(x=end_plot, y=0, ax=start, ay=0, xref="x", yref="y", axref="x", ayref="y", showarrow=True, arrowhead=2, arrowsize=1.2, arrowwidth=3, arrowcolor="#00b4d8")\n')
    
    # Adicionando assíntotas
    r(ind + '        if nP != nZ:\n')
    r(ind + '            for q, a in enumerate(angles_A):\n')
    r(ind + '                rad = np.radians(a)\n')
    r(ind + '                t_vals = []\n')
    r(ind + '                if np.cos(rad) > 1e-5:\n')
    r(ind + '                    t_vals.append((xmax - np.real(sigma_A)) / np.cos(rad))\n')
    r(ind + '                elif np.cos(rad) < -1e-5:\n')
    r(ind + '                    t_vals.append((xmin - np.real(sigma_A)) / np.cos(rad))\n')
    r(ind + '                if np.sin(rad) > 1e-5:\n')
    r(ind + '                    t_vals.append((ymax - 0) / np.sin(rad))\n')
    r(ind + '                elif np.sin(rad) < -1e-5:\n')
    r(ind + '                    t_vals.append((ymin - 0) / np.sin(rad))\n')
    r(ind + '                t_vals = [t for t in t_vals if t > 0]\n')
    r(ind + '                t_draw = min(t_vals) if t_vals else max(2.0, max(xmax-xmin, ymax-ymin)*0.8)\n')
    r(ind + '                head_x = np.real(sigma_A) + t_draw * np.cos(rad)\n')
    r(ind + '                head_y = t_draw * np.sin(rad)\n')
    r(ind + '                fig_simp.add_trace(go.Scatter(x=[np.real(sigma_A), head_x], y=[0, head_y], mode="lines", line=dict(color="orange", width=2, dash="dash"), showlegend=False))\n')
    
    # Adicionando os ramos curvos
    r(ind + '        for branch_idx in range(all_roots.shape[1]):\n')
    r(ind + '            b_real = np.real(all_roots[:, branch_idx])\n')
    r(ind + '            b_imag = np.imag(all_roots[:, branch_idx])\n')
    r(ind + '            fig_simp.add_trace(go.Scatter(x=b_real, y=b_imag, mode="lines", line=dict(width=3, color="#00b4d8"), showlegend=False))\n')
    
    r(ind + '        st.plotly_chart(fig_simp, width="stretch", config={"scrollZoom": True})\n')
    r(ind + '        st.markdown("---")\n')
    r(ind + '        \n')
    
    # Item B
    r(ind + '    if show_item_b:\n')
    r(ind + '        st.markdown("### ▼ ITEM (b): TESTE DE PONTO CANDIDATO E GANHO K")\n')
    r(ind + '        s0_str = format_complex_frac(s0)\n')
    r(ind + '        st.markdown(f"**Ponto testado:** $s_i = {s0_str}$")\n')
    r(ind + '        test_details = evaluate_test_point_details(s0, poles, zeros, D_coeffs, N_coeffs, atol_deg=tol_deg)\n')
    r(ind + '        \n')
    r(ind + '        st.markdown("**• Critério de Ângulo (Pertinência ao LGR):**")\n')
    r(ind + '        sum_z_terms_list = []\n')
    r(ind + '        for vz in test_details["vecs_z"]:\n')
    r(ind + '            st.markdown(f"&nbsp;&nbsp; - Do zero $z_{{{vz[\'index\']}}} = {format_root(vz[\'zero\'])}$ até $s_i$: $\\\\phi_{{{vz[\'index\']}}} = {format_frac(vz[\'angle_deg\'])}^\\\\circ$")\n')
    r(ind + '            sum_z_terms_list.append(f"({format_frac(vz[\'angle_deg\'])}°)")\n')
    r(ind + '        if not test_details["vecs_z"]:\n')
    r(ind + '            st.markdown("&nbsp;&nbsp; - Não há zeros na malha aberta.")\n')
    r(ind + '        \n')
    r(ind + '        sum_p_terms_list = []\n')
    r(ind + '        for vp in test_details["vecs_p"]:\n')
    r(ind + '            st.markdown(f"&nbsp;&nbsp; - Do pólo $p_{{{vp[\'index\']}}} = {format_root(vp[\'pole\'])}$ até $s_i$: $\\\\theta_{{{vp[\'index\']}}} = {format_frac(vp[\'angle_deg\'])}^\\\\circ$")\n')
    r(ind + '            sum_p_terms_list.append(f"({format_frac(vp[\'angle_deg\'])}°)")\n')
    r(ind + '        if not test_details["vecs_p"]:\n')
    r(ind + '            st.markdown("&nbsp;&nbsp; - Não há pólos na malha aberta.")\n')
    r(ind + '        \n')
    r(ind + '        sum_z_terms = " + ".join(sum_z_terms_list) or "0°"\n')
    r(ind + '        sum_p_terms = " + ".join(sum_p_terms_list) or "0°"\n')
    r(ind + '        total_angle = test_details["total_angle"]\n')
    r(ind + '        is_lgr = test_details["is_lgr"]\n')
    r(ind + '        if is_lgr:\n')
    r(ind + '            st.latex(f"\\\\Sigma \\\\phi_j - \\\\Sigma \\\\theta_i = ({sum_z_terms}) - ({sum_p_terms}) = {format_frac(total_angle)}^\\\\circ \\\\approx \\\\pm 180^\\\\circ")\n')
    r(ind + '            st.success(f"**RESULTADO: O PONTO PERTENCE AO LGR (Tolerância: ±{tol_deg}°)**")\n')
    r(ind + '            \n')
    r(ind + '            st.markdown("**• Critério de Módulo (Cálculo de K):**")\n')
    r(ind + '            dist_p_terms_list = []\n')
    r(ind + '            for vp in test_details["vecs_p"]:\n')
    r(ind + '                st.markdown(f"&nbsp;&nbsp; - Distância do pólo $p_{{{vp[\'index\']}}}$ até $s_i$: $d_{{p{vp[\'index\']}}} = {format_frac(vp[\'dist\'])} $")\n')
    r(ind + '                dist_p_terms_list.append(format_frac(vp["dist"]))\n')
    r(ind + '            dist_z_terms_list = []\n')
    r(ind + '            for vz in test_details["vecs_z"]:\n')
    r(ind + '                st.markdown(f"&nbsp;&nbsp; - Distância do zero $z_{{{vz[\'index\']}}}$ até $s_i$: $d_{{z{vz[\'index\']}}} = {format_frac(vz[\'dist\'])} $")\n')
    r(ind + '                dist_z_terms_list.append(format_frac(vz["dist"]))\n')
    r(ind + '            \n')
    r(ind + '            dist_p_terms = " \\\\cdot ".join(dist_p_terms_list) or "1"\n')
    r(ind + '            dist_z_terms = " \\\\cdot ".join(dist_z_terms_list) or "1"\n')
    r(ind + '            scale_factor = (abs(N_coeffs[0])/abs(D_coeffs[0])) if D_coeffs[0] != 0 else 1.0\n')
    r(ind + '            scale_str = f"{format_frac(scale_factor)} \\\\cdot " if scale_factor != 1.0 else ""\n')
    r(ind + '            K_val = test_details["K"]\n')
    r(ind + '            st.latex(f"K = \\\\frac{{\\\\prod d_{{pi}}}}{{{scale_str}\\\\prod d_{{zj}}}} = \\\\frac{{{dist_p_terms}}}{{{scale_str}{dist_z_terms}}} = {format_frac(K_val)}")\n')
    r(ind + '            st.success(f"**RESULTADO: K = {format_frac(K_val)}**")\n')
    r(ind + '        else:\n')
    r(ind + '            st.latex(f"\\\\Sigma \\\\phi_j - \\\\Sigma \\\\theta_i = ({sum_z_terms}) - ({sum_p_terms}) = {format_frac(total_angle)}^\\\\circ \\\\neq \\\\pm 180^\\\\circ")\n')
    r(ind + '            st.error(f"**RESULTADO: O PONTO NÃO PERTENCE AO LGR (Fora da tolerância de ±{tol_deg}°)**")\n')
    r(ind + '        \n')
    r(ind + '        st.markdown("**Gráfico dos Vetores:**")\n')
    r(ind + '        fig_test = plot_test_point_vectors(poles, zeros, s0, test_details, xmin, xmax, ymin, ymax)\n')
    r(ind + '        st.plotly_chart(fig_test, width="stretch", config={"scrollZoom": True})\n')

    out = lines[:262] + replacement + lines[359:]
    with open('app.py', 'w', encoding='utf-8') as f:
        f.writelines(out)

modify()
